# Generated by Django 5.2.4 on 2025-10-24 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_gender_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
